#!/bin/bash

rm dist/*

git submodule foreach git reset --hard
git submodule update --remote 

mv ./src/stuscraper/stu-cli.py ./src/stuscraper/__init__.py

sed -i "s/packagebuild = False/packagebuild = True/" src/stuscraper/__init__.py

python3 -m build

python3 -m twine upload dist/*
