#!/bin/bash

rm dist/*

git submodule foreach git restore --staged --source=HEAD --worktree -- .
git submodule foreach git clean -f -- .
git submodule update --remote --merge

mv ./src/stuscraper/stu-cli.py ./src/stuscraper/__init__.py

sed -i "s/packagebuild = False/packagebuild = True/" src/stuscraper/__init__.py

python3 -m build

echo "Upload to PyPi? [y/N]"
read cont
if [ "$cont" != "y" ]; then
	exit 0
fi

sleep 2
python3 -m twine upload dist/*
